### ISSUE TITLE
Add points

### ISSUE THREAD

**Issue by cqvu** [MLH-Fellowship/fellow-central#29]
## Task(s)
- [x] For Discord: check if messages limit reached (5 per day)
- [x] For event: check if Point with eventId already exist, reject if so
- [x] Add a Point to table with appropriate fields
- [x] ~~Increment total points for the User~~

**Comment by luiszugasti** [comment]
pseudo code for that (Should get you all the events you need within the last day)
This one will get you the amount of hits from the engine, I mean you could also just add a boolean from there and should be good to go.

SELECT COUNT(*)
FROM
(
SELECT * FROM events WHERE timestamp < {predefined_time_stamp} AND timestamp > {predefined_time_stamp - 24 hours}
)
->>> gets you the count :)

**Comment by cqvu** [comment]
Removing the "Increment total points for the User" requirement because we decided to remove points_total for the user model to reduce redundancy
